### ISSUE TITLE
文本改进建议

### ISSUE THREAD

**Issue by kidonng** [Littlegolden/flarum-lang-simplified-chinese#2]
您好，我一年多前给 Csineneo 的简中翻译提过 PR，因为文本量较大，细节处理不善，很高兴看到有其他简中用户制作更本土化的翻译，提一点拙见。

- https://github.com/Littlegolden/flarum-lang-simplified-chinese/blob/1ad012f690ceba5d25c1e477846e980783f6b535/locale/core.yml#L48
  ```diff
  - forum_description_text: '输入一两句话简单描述论坛。这将会显示为<Meta name="description"> 标签，并出现在搜索引擎结果中。'
  + forum_description_text: '输入一两句话简单描述论坛。这将会显示为 <meta name="description"> 标签，并出现在搜索引擎结果中。'
  ```
  Flarum 主打简约风格，个人在补充描述原文前，一般会评价补充文本能否实质性帮助理解上下文，比如说如果不加备注，用户不一定能意识到“[站点图标](https://github.com/Csineneo/lang-simplified-chinese/blob/68c9181b5293cb887a5309b69e22e2372d657aab/locale/core.yml#L33)”指的是 favicon。这仅是个人偏好，但既然要补充描述就最好力求准确~~其实只是强迫症~~。
- https://github.com/Littlegolden/flarum-lang-simplified-chinese/blob/1ad012f690ceba5d25c1e477846e980783f6b535/locale/core.yml#L98
  "Mail driver" 中的 driver 一次用法比较特殊，我之前翻译为“模式”以便理解，如果要用“驱动”一词，建议写为“邮件驱动”，避免用户产生疑惑。
- 用语统一，比如“帖子”和“主题”，“账号”、“帐号”和“用户”等。
- 最后跑下题，自立门户初衷是好的，但 Csineneo 的版本存在时间较久，已有很多用户，此版本不易被发现，可以考虑和 Csineneo 的版本合并，或者在 Csineneo 的版本处放一个此版本的链接，相信 Csineneo 应该会同意简中用户亲自维护的翻译。

**Comment by littlegolden** [comment]
感谢提出建议！
1. meta 没注意到有个大写，已修正。

2. Favicon 可以翻译成「站点图标」「网页图标」「网站图标」，之所以选择「站点图标」确实是因为叫的顺口，加入下面的描述如何？欢迎提出改进。
  ```diff
  -  favicon_text: 上传图片做为论坛的站点图标。
  + favicon_text: 上传图片做为论坛的站点图标，该图标会显示在浏览器标签页、搜索引擎结果条目及书签等多个地方。
  ```

3. 翻译「Mail Driver」时，参照了 learnku 等网站翻译的开发文档，比如「[Mailgun 驱动](https://learnku.com/docs/laravel/5.6/mail/1392#bf7c2a)」，最终决定沿用「驱动」不变。「邮件驱动」的补充很好，已采纳。

4. 关于「帖子 / 主题」，正经的名词应该是「主题帖」「回复帖」，统称为「帖子」，论坛中对于主题帖的操作/功能，使用的是「主题」一词，对于主题帖和回复帖皆可的操作/功能，使用的是「帖子」一词。其实有想过「帖子」一词不够高大上，但是考虑到如果对通用的功能使用「主题帖和回复帖」会导致翻译文本过长，因此最终妥协了。

5. 「用户」和「账号」。刚刚检查了一遍，发现使用「账号」的地方多是第三方登录扩展程序的翻译，使用「用户」的地方多是针对用户本身操作而言的。比如下面的[删除用户操作](https://github.com/Littlegolden/flarum-lang-simplified-chinese/blob/1ad012f690ceba5d25c1e477846e980783f6b535/locale/core.yml#L79)，第一步是点击删除按钮（此处按钮引用的是通用翻译「删除」一词），然后弹窗提示，最后操作完成。
```yml
delete_button: => core.ref.delete
delete_confirmation: "确定要删除此用户？此账号会被注销，已发布的帖子仍会保留。"
delete_error_message: "删除用户 <i>{username} ({email})</i> 失败"
delete_success_message: "用户 <i>{username} ({email})</i> 已删除"
```
这里翻译时的出发点是，多数情况下，管理员想要删除用户是因为某个用户发广告、发布垃圾信息，这是用删除的说法是最好的。少数情况下，是用户自己需要注销自己不再使用的账号，但目前 Flarum 并没有用户自行申请注销账号的功能，因此最终我在这里使用「删除用户」而非「删除账号」。

6. 「账号」和「帐号」，「帐号」是错别字，之前明明全局替换过的，没想到还有遗漏的。

7. 自己翻译简中语言包的初衷是发现 CS 的版本有一点点不足，有提交过 PR，但是发现 CS 的反应时间不是很稳定，考虑到自己站点的需求，加之疫情影响时间很充裕，于是就有了此版本的语言包。暂不会考虑与 CS 的版本合并，毕竟 CS 他/她已维护许久，合并、留链接的行为有些冒犯。

**Comment by kidonng** [comment]
感谢回复！

> 2\. Favicon 可以翻译成「站点图标」「网页图标」「网站图标」，之所以选择「站点图标」确实是因为叫的顺口，加入下面的描述如何？欢迎提出改进。

保持现有状态就好了，我只是用来举例。

> 5\. 「用户」和「账号」。刚刚检查了一遍，发现使用「账号」的地方多是第三方登录扩展程序的翻译，使用「用户」的地方多是针对用户本身操作而言的。比如下面的[删除用户操作](https://github.com/Littlegolden/flarum-lang-simplified-chinese/blob/1ad012f690ceba5d25c1e477846e980783f6b535/locale/core.yml#L79)，第一步是点击删除按钮（此处按钮引用的是通用翻译「删除」一词），然后弹窗提示，最后操作完成。

“用户”和“账号”各有各的使用场景，我指的是在各自适合的场景应该统一。您举例中的情形是管理员操作用户，自然不存在“账号”的概念。



> 7\. 自己翻译简中语言包的初衷是发现 CS 的版本有一点点不足，有提交过 PR，但是发现 CS 的反应时间不是很稳定，考虑到自己站点的需求，加之疫情影响时间很充裕，于是就有了此版本的语言包。暂不会考虑与 CS 的版本合并，毕竟 CS 他/她已维护许久，合并、留链接的行为有些冒犯。

有需求才会有衍生版本嘛，我也仅是建议，此版本的翻译稳定后也可以适当提交到 Csineneo。
