### ISSUE TITLE
Carbon 1 is deprecated

### ISSUE THREAD

**Issue by firstC99** [Littlegolden/flarum-lang-simplified-chinese#3]
After running the “composer require” command, the following prompt appears: 

Carbon 1 is deprecated, see how to migrate to Carbon 2.

**Comment by littlegolden** [comment]
As [Franz stated here](https://discuss.flarum.org/d/20607-upgrade-carbon-beta-9/5) this is just a warning for developers. You can ignore it.

> This is just a warning message for developers and means that `Laravel` or `Flarum` should take the time to update the Carbon dependency. It shouldn't cause any problems for you.

如 [Franz 所说](https://discuss.flarum.org/d/20607-upgrade-carbon-beta-9/5)，这只是个给开发者的警告，需要 Laravel 或 Flarum 升级，咱们用户无用理睬。
