### ISSUE TITLE
 首次接触forum js有个报错forum-zh-Hans-70164310.js:13 Uncaught TypeError: moment.defineLocale is not a function

### ISSUE THREAD

**Issue by BrothelUndercover** [Littlegolden/flarum-lang-simplified-chinese#9]
![image](https://user-images.githubusercontent.com/46702134/96972820-94e89b00-1549-11eb-8ce6-e72b3fa028de.png)
Flarum 0.1.0-beta.14
flarum-lang-simplified-chinese": "^0.1.68

**Comment by littlegolden** [comment]
您需要安装最新版本：
```
composer require littlegolden/flarum-lang-simplified-chinese:^v0.1.70
php flarum cache:clear
```

**Comment by BrothelUndercover** [comment]
> 您需要安装最新版本：
> 
> ```
> composer require littlegolden/flarum-lang-simplified-chinese:^v0.1.70
> php flarum cache:clear
> ```
回复效率真高
